services:
  webpage:
    container_name: webpage
    hostname: webpage
#    depends_on:
#      - typedb
    build:
      context: ./
      dockerfile: ./Dockerfile.ubuntu
    working_dir: /var/app/current
    env_file:
      - ./.env
    ports:
      - "${WEBPAGE_HOST_PORT}:${WEBPAGE_CONTAINER_PORT}"
      - "${WEBPAGE_HOST_DEBUG_PORT}:${WEBPAGE_CONTAINER_DEBUG_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - "./:/var/app/current"
    command: sh -c "bash /var/app/current/docker_init.sh"